### ISSUE TITLE
Time Varying GHG

### ISSUE THREAD

**Issue by HoWol76** [coecms/esm-pmip-last-mil#2]
CO2, N2O, CH4: time varying, and included in the CMIP6 GHG forcing data set (so it might already be downloaded for the historical runs). Data is via http://climatecollege.unimelb.edu.au/cmip6 . I’m not sure which format is needed for ACCESS-ESM

Make UMUI job with static and time-varying data, see what changes.

**Comment by HoWol76** [comment]
Made two jobs with UMUIX, one with time varying concentrations, one with constant concentrations. Here's the differences:

in `CNTLATM`, the entries for `CO2MMR` and so on disappear from the namelist `RUN_Radiation`. New entries appear in the namelist `CLMCHFCG`:

- `L_CLMCHFCG` (Changed to True)
- `CLIM_FCG_NYEARS(1)` (156)
- `CLIM_FCG_YEARS(1,1)` (Years that data is given for, I assume 156 in total)
- `CLIM_FCG_LEVLS(1,1)` (An array with the starting value of 4.32598e-04)
- `CLIM_FCG_RATES(1,1)` (An array consisting only of values -32786.0 (Missing Value?))
The pattern of arrays then repeats, same array names, different last index. Probably different species.

| Index | Initial Value | Final Value | Species |
| ---: | ---: | ---: | :---- |
| 1 | 4.32598e-04 || CO2 |
| 2 | 4.38078e-07 || CH4 |
| 3 | 4.18499e-07 || N2O |
| 4 | 0.00000e+00 | 1.20505e-09 | CFC11 |
| 5 | 0.00000e+00 | 2.25164e-09 | CFC12 |
| 6 | Does not appear | |
| 7 | Does not appear | |
| 8 | 0.00000e+00 | 5.13044e-10 | CFC113 |
| 9 | 0.00000e+00 | 4.84345e-10 | HCFC22 |
| 10 | 0.00000e+00 | 1.50252e-11 | HFC125 |
| 11 | 0.00000e+00 | 1.21031e-10 | HFC134A |

**Comment by HoWol76** [comment]
As data I found this download at the address provided above: http://www.geosci-model-dev.net/10/2057/2017/gmd-10-2057-2017-supplement.zip

There's an Excel file in there that has dedicated sheets for CO2, N2O, CH4, etc.
These sheets contain, after some documentation, tables for the values in 4 columns (year, global, northern and southern hemisphere (I assume that's what NH and SH stand for))

**Comment by HoWol76** [comment]
It seems that the values supplied are in ppm/ppb/ppt, whereas I'm fairly certain UM needs them in MMR. So conversion is needed.

**Comment by HoWol76** [comment]
Wondering, what is the difference between CFC-11 and CFC-11eq (similarly CFC-12)

**Comment by HoWol76** [comment]
Check which values were used by the historical run

**Comment by HoWol76** [comment]
Claire suggests that the -eq concentrations are what would be needed to be added to CO2 in order to have the same effect (in case the model doesn't deal with this gas specifically).

**Comment by nickywright** [comment]
Link to paper: https://gmd.copernicus.org/articles/10/2057/2017/gmd-10-2057-2017.pdf, see Section 2.1.10 (paragraph before Section 2.2) and Table 5

**Comment by HoWol76** [comment]
1. Option 1: climate models implement a subset of 43
GHGs.
2. Option 2: climate models implement the four most important GHGs with their actual mole fractions explicitly, namely CO2, CH4, N2O and CFC-12, and summarize the effect of all other 39 gases in an equivalence
concentration of CFC-11. For this purpose, we provide
CFC-11 eq. concentrations (“full equivalence”).
3. Option 3: like option 2, but with a different split up of
gases other than CO2, CH4 and N2O. Climate models
implement the three most important GHGs with their
actual mole fractions explicitly, namely CO2, CH4 and
N2O, and summarize the radiative effect of the ODSs in
a CFC-12 eq. concentration and the radiative effect of
all other fluorinated gases as a HFC-134a eq. concentration. For this purpose, we provide CFC-12 eq. and HFC134a eq. concentrations (“full equivalence

**Comment by HoWol76** [comment]
Looking at one of the historic runs, these arrays contain values:

| Field | Gas | level for 2014 |
|:----|:----|----:|
|`CLIM_FCG_LEVLS(1,1)`| CO2 | 6.033164e-04 |
|`CLIM_FCG_LEVLS(1,2)`| CH4 |  1.013009e-06 |
|`CLIM_FCG_LEVLS(1,3)`| N2O | 4.962693e-07 |
|`CLIM_FCG_LEVLS(1,4)`| CFC11 | 1.104076e-09 |
|`CLIM_FCG_LEVLS(1,5)` | CFC12 | 2.170460e-09 |
|`CLIM_FCG_LEVLS(1,8)` | CFC113 | 4.698008e-10 |
|`CLIM_FCG_LEVLS(1,9)` | HCFC22 | 6.844250e-10 |
|`CLIM_FCG_LEVLS(1, 10)` | HFC125  | 6.354852e-11 |
|`CLIM_FCG_LEVLS(1, 11)` | HFC134A | 2.832775e-10 |

**Comment by HoWol76** [comment]
The UM in `src/atmosphere/short_wave_radiation/csenario_mod.F90` declares the parameter `LENSCEN` as the maximum length of scenarios.

This value is currently 800, and it is used to dimension the variables `CLIM_FCG_YEARS`, `CLIM_FCG_LEVLS`, and `CLIM_FCG_RATES`

**Comment by HoWol76** [comment]
Created a new build with this number increased to 1300: `/scratch/w35/hxw599/access-esm/pmip-lm/build/bin/um_hg3.exe-20200903`

**Comment by HoWol76** [comment]
Seems to work now.
